### ISSUE TITLE
Liam is not accepting PRs

### ISSUE THREAD

**Issue by hotcocoaNcode** [OmegaGodzilla66/PYSON#7]
Issue described in title.

**Comment by ProbablyComputingSquid** [comment]
This is such a pressing issue, @OmegaGodzilla66 please fix this

**Comment by nmd102** [comment]
This issue is crucial for PYSON to work @OmegaGodzilla66 please fix this

**Comment by hotcocoaNcode** [comment]
He accepted a pull request guys 🥳
